name: Download Mihomo Tool
on:
  schedule:
    - cron: '0 */8 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          mkdir -p ./data
          sudo chown -R $USER:$USER ./data

      - name: Get and compare versions
        id: version
        run: |
          # 获取最新版本（去除可能的v前缀）
          LATEST_VERSION=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/latest/download/version.txt | sed 's/^v//')
          echo "latest_version=${LATEST_VERSION}" >> $GITHUB_ENV

          # 检查本地版本
          if [[ -f "./data/mihomo-linux-amd64" ]]; then
            CURRENT_VERSION=$("./data/mihomo-linux-amd64" -v 2>/dev/null | awk '{print $2}' | sed 's/^v//' || echo "")
            echo "current_version=${CURRENT_VERSION}" >> $GITHUB_ENV
          fi

          # 设置是否需要下载
          if [[ "$LATEST_VERSION" != "$CURRENT_VERSION" ]]; then
            echo "needs_download=true" >> $GITHUB_ENV
            echo "::notice::New version available: v${LATEST_VERSION}"
          else
            echo "::notice::Already up-to-date (v${LATEST_VERSION})"
          fi

      - name: Download binary
        if: env.needs_download == 'true'
        run: |
          echo "::group::Downloading mihomo v${LATEST_VERSION}"
          TEMP_FILE=$(mktemp)
          curl -sLo "${TEMP_FILE}.gz" \
            "https://github.com/MetaCubeX/mihomo/releases/latest/download/mihomo-linux-amd64-v${LATEST_VERSION}.gz"
          
          gunzip "${TEMP_FILE}.gz"
          mv "$TEMP_FILE" ./data/mihomo-linux-amd64
          chmod +x ./data/mihomo-linux-amd64
          echo "::endgroup::"

      - name: Commit changes
        if: env.needs_download == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add ./data/mihomo-linux-amd64
          git diff-index --quiet HEAD || (git commit -m "chore: Update mihomo to v${LATEST_VERSION}" && git push)